import { weapons } from "./Weapons";

export const monsters = {
  goblin: {
    displayName: "Гоблин",
    hp: 5,
    strength: 1,
    agility: 1,
    stamina: 1,
    reward: weapons.dagger,
    weaponDamage: 2,
  },
  skeleton: {
    displayName: "Скелет",
    hp: 10,
    strength: 2,
    agility: 2,
    stamina: 1,
    reward: weapons.club,
    weaponDamage: 2,
    feature: function () {},
  },
  slime: {
    displayName: "Слайм",
    hp: 8,
    strength: 3,
    agility: 1,
    stamina: 2,
    reward: weapons.spear,
    weaponDamage: 1,
    feature: function () {},
  },
  ghost: {
    displayName: "Призрак",
    hp: 6,
    strength: 1,
    agility: 3,
    stamina: 1,
    reward: weapons.sword,
    weaponDamage: 3,
    feature: function () {},
  },
  golem: {
    displayName: "Голем",
    hp: 10,
    strength: 3,
    agility: 1,
    stamina: 3,
    reward: weapons.axe,
    weaponDamage: 1,
    feature: function () {},
  },
  dragon: {
    displayName: "Дракон",
    hp: 20,
    strength: 3,
    agility: 3,
    stamina: 3,
    reward: weapons.legendarySword,
    weaponDamage: 4,
    feature: function () {},
  },
};
